### ISSUE TITLE
KDE 5.13 runtime is no longer supported

### ISSUE THREAD

**Issue by mMerlin** [flathub/org.fritzing.Fritzing#10]
`flatpak update` on my system is reporting that
`org.kde.Platform is end-of-life, with reason: The KDE 5.13 runtime is no longer supported and does not receive security updates. We strongly recommend migrating to a supported runtime.`

The (apparently) latest update for org.fritzing.Fritzing is using that.

```sh
% flatpak info org.fritzing.Fritzing

Fritzing - Electronic Design Tool

          ID: org.fritzing.Fritzing
         Ref: app/org.fritzing.Fritzing/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.9.4b
     License: GPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 186.2 MB
     Runtime: org.kde.Platform/x86_64/5.13
         Sdk: org.kde.Sdk/x86_64/5.13

      Commit: c595162a1d06f01eab9b66092c7ca68518974b9887295cd59950c439bfba3a72
      Parent: 39bbd0e2b1e2740293803fd4dc550fb0b1827dc5ddccff56a07f7aedad9c2aa5
     Subject: Add OARS info (7dec8699)
        Date: 2019-12-18 19:56:11 +0000
% flatpak --version
Flatpak 1.4.4
% uname -r
5.8.18-100.fc31.x86_64
```

What does it take to migrate to (and test with) a new platform version? `flatpak list` also shows a 5.15 version in my environment. There might be newer than that available as well.

**Comment by gasinvein** [comment]
Hopefully it'll just work, but the app hasn't a stable release in a year, so who knows. Opened #11, testing welcome.
