### ISSUE TITLE
Opening a FZZ file in file manager opens "Untitled Sketch.fzz" in Fritzing

### ISSUE THREAD

**Issue by bastianilso** [flathub/org.fritzing.Fritzing#4]
I can't open files from my file manager in the flatpak'ed version of fritzing. For now, my workaround is to use File -> Open.. menu in Fritzing.

Is this problem something wit how the filepath is passed on to Fritzing? Is it upstream or something we can fix from the manifest side of things?

**Comment by gasinvein** [comment]
Please have a look at #2 and check if Fritzing behaves in same way in your case. This issue seems related.

**Comment by bastianilso** [comment]
Thanks for fixing this! :))
